name: nf-core linting and stubbing
on:
  push:
  pull_request:

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    container:
      image: mstruebing/editorconfig-checker:v3.2.1
      options: --user root
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Linting
        run: ec --exclude '^.devcontainer/|^.git/|README.md'
  nf-core:
    runs-on: ubuntu-latest
    container:
      image: nfcore/tools:3.2.0
      options: --user root
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Linting
        run: nf-core pipelines lint -w
  prettier:
    runs-on: ubuntu-latest
    container:
      image: jauderho/prettier:3.5.3
      options: --user root
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Linting
        run: prettier -c .
  nextflow:
    runs-on: ubuntu-latest
    container:
      image: nextflow/nextflow:24.10.5
      options: --user root
    steps:
      - name: Install tar
        run: yum install -y tar
      - name: Check out pipeline code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Stubbing
        run: nextflow run . -stub-run -profile test_stub
